project:
  type: website

website:
  title: "The OO-Ray"
  google-analytics: "G-KSSKDNK101"
  navbar:
    right:
      - about.qmd
      - music.qmd
      - videos.qmd
      - press.qmd
      - licensing.qmd
      - href: https://tinyletter.com/ooray
        text: Mailing List
      - icon: twitter
        href: https://twitter.com/ooray
      
format:
  html:
    theme: lux
    css: styles.css



