project:
  type: website

website:
  title: "Website for Ted Laderas/The OO-Ray"
  navbar:
    right:
      - about.qmd
      - music.qmd
      - videos.qmd
      - press.qmd
      - licensing.qmd
      - href: https://tinyletter.com/ooray
        text: Mailing List
      - icon: twitter
        href: https://twitter.com/ooray
      
format:
  html:
    theme: lux
    css: styles.css



