project:
  type: website

website:
  title: "Website for The OO-Ray"
  navbar:
    right:
      - about.qmd
      - music.qmd
      - videos.qmd
      - licensing.qmd
      - icon: twitter
        href: https://twitter.com/ooray
      
format:
  html:
    theme: cosmo
    css: styles.css



